function stypendium(){
    document.getElementById("proces").innerHTML = "<b>Złożenie podania o stypendium:</b><br>Student w Dziekanacie ds. Socjalnych składa wniosek o stypendium. Wniosek jest sprawdzany przed pracownika dziekanatu, jeśli jest wypełniony odpowiednio jest przyjmowany i wpisywany do rejestru. Następnie student oczekuje na informacje na ISOD o decyzjach stypendialnych i decyzję odbiera.";
    
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/Untitled.png' data-lightbox='example1'><img src='diagramy/Untitled.png'/></a>";
}
function naukowe(){
    document.getElementById("proces").innerHTML ="<b>Złożenie podania o Stypendium Rektora dla najlepszych studentów za wyniki w nauce:</b><br> Student pobiera wniosek o Stypendium Rektora  dla najlepszych studentów za wyniki w nauce ze strony <a href='http://www.bss.ca.pw.edu.pl/Do-pobrania/Wnioski-i-formularze/Pomoc-materialna/Wniosek-o-przyznanie-stypendium-rektora-dla-najlepszych-studentow-za-wyniki-w-nauce' target='_blank'>Stypendia</a> i wypełnia niezbędne dane komputerowo. Dołącza Załącznik nr. 9 o niepobieraniu świadczeń pomocy materialnej na więcej niż jednym kierunku studiów. Z uzupełnionym podaniem student przychodzi do Dziekanatu ds. Socjalnych, tam wniosek przyjmowany jest, bądź oddawany do poprawy przez pracownika. Następnie podanie rozpatrzone jest przez Wydziałową Komisję Stypendialną i wpisywane do bazy stypendiów. Kilka dni po zakończeniu akcji stypendialnej publikowana jest wstępna lista rankingowa tworzona przez pracowników Dziekanatu ds. Socjalnych, Student ma w tym momencie tydzień na odwołanie się od decyzji. Po upłynięciu tygodnia publikowana jest oficjalna lista rankingowa. Na koniec student odbiera decyzję dotyczącą stypendium naukowego. ";
    document.getElementById("proces").innerHTML +="<br><br> <b>Uwaga:</b><br> Stypendium przyznawane jest raz do roku - na 10 miesięcy, z wyjątkiem semestru 7 studiów I stopnia oraz 1 semestru studiów II stopnia, gdzie przyznawane jest na okres 5 miesięcy. Stypendium przyznawane jest studentowi, który uzyskał średnią ważoną za poprzedni rok wyższą niż 4,00 z dokładnością do 2 miejsca po przecinku. Stypendium Rektora  dla najlepszych studentów za wyniki w nauce otrzymuje maksymalnie 10% studentów danego rocznika I kat i II kat";
    
    document.getElementById("proces").innerHTML +="<br><br>"   +" <a href='diagramy/Stypendium%20rektora%20za%20wyniki%20w%20nauce.png' data-lightbox='example1'><img src='diagramy/Stypendium%20rektora%20za%20wyniki%20w%20nauce.png'/></a> <br><br> <b>Tworzenie list rankingowych</b><br><a href='diagramy/listy%20rankingowe.jpg' data-lightbox='example1' ><img id='pionowe' src='diagramy/listy%20rankingowe.jpg'/></a>";

}
function sportowe(){
    document.getElementById("proces").innerHTML = "<b>Złożenie podania o stypendium za osiągnięcia naukowe, sportowe lub artystyczne:</b><br> Student pobiera wniosek o przyznanie zapomogi ze strony <a target='_blank' href='hhttp://www.bss.ca.pw.edu.pl/Do-pobrania/Wnioski-i-formularze/Pomoc-materialna/Wniosek-o-przyznanie-stypendium-rektora-dla-najlepszych-studentow-za-osiagniecia-naukowe-artystyczne-lub-wysokie-wyniki-sportowe'>Wniosek</a>. Następnie wypełnia niezbędne dane osobowe komputerowo. Załącza niezbędne dokumenty potwierdzające osiągnięcia. Dołącza również Załącznik nr. 9 o niepobieraniu świadczeń pomocy materialnej na więcej niż jednym kierunku studiów. Uzupełnione podanie student składa w Dziekanacie ds. Socjalnych, następnie jego poprawność weryfikowana jest przez pracownika dziekanatu, który może podania nie przyjąć. Następnie podanie rozpatrzone jest przez Wydziałową Komisję Stypendialną i wpisywane do bazy stypendiów. Na koniec student odbiera decyzję dotyczącą stypendium.";
    document.getElementById("proces").innerHTML +="<br><br> <b>Uwaga:</b><br>    Stypendium może otrzymać student, który zaliczył przynajmniej pierwszy rok studiów lub studiuje przynajmniej na pierwszym roku studiów drugiego stopnia rozpoczętych w ciągu roku od ukończenia studiów pierwszego stopnia, uzyskał rejestrację na kolejny rok lub semestr studiowania, w poprzednim roku studiów oraz  posiadał osiągnięcia naukowe, artystyczne lub sportowe. Więcej informacji student znajdzie na stronie: <a target='_blank' href='https://sspw.pl/pl/student/pomoc-materialna/stypendia'>Stypendia</a>";

    document.getElementById("proces").innerHTML +="<br><br>"   +"<b>Stypendium za osiągnięcia naukowe</b><br><a href='diagramy/Stypendium%20za%20osi%C4%85gni%C4%99cia.png' data-lightbox='example1'><img src='diagramy/Stypendium%20za%20osi%C4%85gni%C4%99cia.png'/></a>   <br><br> <b>Stypendium sportowe / artystyczne</b><br><a href='diagramy/stypendium%20sportowe.jpg' data-lightbox='example1'><img src='diagramy/stypendium%20sportowe.jpg'/></a>  ";
}
function niepelnosprawni(){
    document.getElementById("proces").innerHTML = "<b>Złożenie podania o stypendium dla osób  niepełnosprawnych:</b><br> Student pobiera wniosek o przyznanie zapomogi ze strony <a href='http://www.bss.ca.pw.edu.pl/Do-pobrania/Wnioski-i-formularze/Pomoc-materialna/Wniosek-o-przyznanie-stypendium-specjalnego-dla-osob-niepelnosprawnych' target='_blank'>Wniosek</a>. Następnie wypełnia niezbędne dane osobowe komputerowo. Załącza niezbędne dokumenty potwierdzające niepełnosprawność oraz oświadczenie o zgodzie na przetwarzanie danych osobowych osób niepełnosprawnych. Dołącza również Załącznik nr. 9 o niepobieraniu świadczeń pomocy materialnej na więcej niż jednym kierunku studiów. Uzupełnione podanie student składa w Dziekanacie ds. Socjalnych, następnie jego poprawność weryfikowana jest przez pracownika dziekanatu, który może podania nie przyjąć. Następnie podanie rozpatrzone jest przez Wydziałową Komisję Stypendialną i wpisywane do bazy stypendiów. Na koniec student odbiera decyzję dotyczącą stypendium.";
    document.getElementById("proces").innerHTML +="<br><br> <b>Uwaga:</b><br>          Stypendium specjalne może otrzymać każdy student, który posiada orzeczenie ustalające stopień niepełnosprawności lub orzeczenie traktowane na równi z orzeczeniem ustalającym stopień niepełnosprawności na podstawie przepisów ustawy z dnia 27 sierpnia 1997r. o rehabilitacji zawodowej i społecznej oraz zatrudnianiu osób niepełnosprawnych. Więcej informacji student znajdzie na stronie: <a href='https://sspw.pl/pl/student/pomoc-materialna/stypendia' target='_blank'>Stypendia</a>. <br><br>Wniosek o stypendium specjalne dla osób niepełnosprawnych można złożyć w dowolnym momencie roku akademickiego. ";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/Niepel.png' data-lightbox='example1'><img src='diagramy/Niepel.png'/></a>";
}
function socjalne(){
    document.getElementById("proces").innerHTML = "<b>Złożenie podania o stypendium socjalne:</b><br>  <br>  Student pobiera wniosek o stypendium socjalne ze strony <a href='http://www.bss.ca.pw.edu.pl/Do-pobrania/Wnioski-i-formularze/Pomoc-materialna/Wniosek-o-przyznanie-stypendium-socjalnego' target='_blank'>Wniosek</a> i wypełnia niezbędne dane komputerowo. Z uzupełnionym wg. Diagramu czynności podaniem oraz niezbędnymi dokumentami student przychodzi do Dziekanatu ds. Socjalnych, tam wniosek przyjmowany jest, bądź oddawany do poprawy przez pracownika. Następnie podanie rozpatrzone jest przez Wydziałową Komisję Stypendialną i wpisywane do bazy stypendiów. Na koniec student odbiera decyzję dotyczącą stypendium socjalnego.";
    document.getElementById("proces").innerHTML +="<br><br> <b>Uwaga:</b><br>          Stypendium przyznawane jest raz do roku - na 10 miesięcy, z wyjątkiem semestru 7 studiów I stopnia oraz 1 semestru studiów II stopnia, gdzie przyznawane jest na okres 5 miesięcy. <br><br>  Stypendium można pobierać wyłącznie na jednym kierunku studiów. <br> <br>Instrukcja wypełniania wniosku dostępna jest na stronie: <a href='http://www.bss.ca.pw.edu.pl/Do-pobrania/Wnioski-i-formularze/Pomoc-materialna/Instrukcja-wypelniania-wniosku-o-stypendium-socjalne' target='_blank'>Stypendium Socjalne</a>. <br><br>Warto również zapoznać się z poradnikiem stypendialnym: <a href='https://sspw.pl/pl/poradnik-stypendialny' target='_blank'>Stypendia</a>";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/stypendium%20socjalne.png' data-lightbox='example1'><img src='diagramy/stypendium%20socjalne.png'/></a> <br><b>Diagram czynności</b><br><a href='diagramy/Socjalne.jpg' data-lightbox='example1'><img id='pionowe' src='diagramy/Socjalne.jpg'/></a>";
}

function zapomoga(){
    document.getElementById("proces").innerHTML = "<b>Złożenie podania o zapomogę:</b>"  +  "<br>Student pobiera wniosek o przyznanie zapomogi ze strony <a href='http://www.bss.ca.pw.edu.pl/Pomoc-materialna/Zapomoga' target='_blank'>Zapomoga</a>. Następnie wypełnia niezbędne dane osobowe komputerowo oraz uzasadnia swoją prośbę. Załącza niezbędne dokumenty potwierdzające, znalezienie się z przyczyn losowych, przejściowo w trudnej sytuacji materialnej. Uzupełnione podanie student składa w Dziekanacie ds. Socjalnych, następnie jego poprawność weryfikowana jest przez pracownika Dziekanatu, który może podania nie przyjąć. Podanie rozpatrzone jest przez Wydziałową Komisję Stypendialną i wpisywane do bazy zapomóg. Student musi odebrać decyzję dotyczącą zapomogi.<br><br>"  +  "<b>Uwaga:</b><br> Podanie przyznawane jest 2 razy do roku - dopuszczalne jest 2 razy w tym samym semestrze. Zdarzenie nie mogło się wydarzyć dawniej niż 3 miesiące temu. Zapomoga nie może być przyznana dwa razy na to samo zdarzenie. Więcej informacji na temat zapomóg można znaleźć na stronie: <a target='_blank' href='https://sspw.pl/pl/student/pomoc-materialna/stypendia' target='_blank'>Stypendia</a>";
    
    document.getElementById("proces").innerHTML +="<br><br>"   +" <a class='example-image-link' href='diagramy/Zapomoga.png' data-lightbox='example1'><img src='diagramy/Zapomoga.png'/></a>";
}

function stopien1(){
    document.getElementById("proces").innerHTML = "<b>Rejestracja na studia I stopnia:</b><br>    Kandydat na studia rejestruje się na stronie <a href='zapisy.pw.edu.pl' target='_blank'>zapisy.pw.edu.pl</a>. Składa swoją preferencję kierunków w kolejności od 1 do 5. Po rejestracji wnosi opłatę, załącz plik ze zdjęciem cyfrowym oraz wprowadza oceny maturalne i czeka na wyniki rekrutacji. W momencie dostania się (wyniki dostępne na stronie <a href= 'www.pw.edu.pl/Kandydaci' target='_blank'>Kandydaci</a> oraz na stronie zgłoszeniowej, po zalogowaniu), kandydat składa niezbędne dokumenty (tj. Świadectwo dojrzałości wraz z kserokopią, dowód osobisty wraz z kserokopią, 2 aktualne fotografię, podpisane na odwrocie imieniem i nazwiskiem) w Dziekanacie ds. Studiów. Wydziałowa Komisja Rekrutacyjna przyjmuje dokumenty i wydaje decyzję razem z umową oraz przekazuje skierowanie na badania lekarskie. Kandydat robi badania oraz przynosi zaświadczenie o możliwości studiowania. Kandydat podpisuje ślubowanie, umowę z wydziałem i odbiera legitymację.<br><br>";
         document.getElementById("proces").innerHTML +=" <b>Uwaga:</b><br>          Jeśli kandydat nie podpisze ślubowania, skreślany jest z listy studentów.<br>   Dokumenty składane mogą być osobiście, bądź przez osobę upoważnioną – formularz dostępny na <a href='www.pw.edu.pl/Kandydaci' target='_blank'>Kandydaci</a>";
    document.getElementById("proces").innerHTML +="<br><br>" + "<a href='diagramy/Rejestracja_na_Studia_1_stopien.png' data-lightbox='example1'><img src='diagramy/Rejestracja_na_Studia_1_stopien.png'/></a>";
}
function stopien2(){
    document.getElementById("proces").innerHTML = "<b>Rejestracja na studia II stopnia:</b><br>Kandydat na studia rejestruje się na stronie <a href='zapisy.pw.edu.pl' target='_blank'>zapisy.pw.edu.pl</a>. Składa preferencję kierunku - jednego. Po rejestracji wnosi opłatę i czeka na wyniki rekrutacji. W momencie dostania się, kandydat składa niezbędne dokumenty. Jeśli ma braki względem studiów inżynierskich, to musi je uzupełnić i tą różnicę programową ustala z Prodziekanem ds. Studiów. Wydziałowa Komisja Rekrutacyjna przyjmuje dokumenty i wydaje decyzję razem z umową i daje skierowanie na badania lekarskie. Student robi badania i przynosi zaświadczenie o możliwości studiowania.";
     document.getElementById("proces").innerHTML +="<br><br> <b>Uwaga:</b><br>          Wydziałowa Komisja Rekrutacyjna może zaprosić Studenta na rozmowę kwalifikacyjną, bądź egzamin w celu weryfikacji wiedzy. ";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a class='example-image-link' href='diagramy/Rejestracja_na_Studia_2_stopien.png' data-lightbox='example1'><img src='diagramy/Rejestracja_na_Studia_2_stopien.png'/></a>";
}
function warunek(){
       document.getElementById("proces").innerHTML = "<b>Złożenie podania o warunkowe przyjęcie na studia:</b><br>      W momencie nie uzyskania przez studenta wystarczającej do przejścia na kolejny semestr punktów ECTS lub w momencie gdy student posiada braki większe niż 1 rok, musi złożyć podanie o warunkowe przyjęcie na studia. Podanie takie można składać na platformie ISOD. W podaniu student musi wypisać wszystkie niezdane przedmioty i uzasadnić czemu powinien dostać się na kolejny semestr. Podanie rozpatrzone jest przez Prodziekana ds. Studiów. Prodziekan może przyjąć podanie, zaproponować studentowi powtarzanie roku lub skreślić go z listy studentów.";
     document.getElementById("proces").innerHTML +="<br><br> <b>Uwaga:</b><br>          Podanie o rejestrację warunkową musi być złożone przed dniem automatycznej rejestracji na kolejny etap. Termin ten jest podany w Kalendarzu Dziekanatu. Podania składane po tym terminie nie będą przez Dziekana rozpatrywane z wyjątkiem sytuacji gdzie skreślenie nastąpiło w wyniku błędnego wyliczenia punktów przez system informatyczny. ";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/Warunkowe%20przyj%C4%99cia%20na%20studia.png' data-lightbox='example1'><img src='diagramy/Warunkowe%20przyj%C4%99cia%20na%20studia.png'/></a>";
}
function transfer(){
    document.getElementById("proces").innerHTML = "<b>Złożenie podania o transfer ocen:</b><br>Student wypełnia wniosek PD_153 o transfer ocen dostępny na stronie <a href='https://isod.ee.pw.edu.pl/isod-portal/dokumenty' target='_blank'>isod.ee.pw.edu.pl/isod-portal/dokumenty</a>. Do podania załącza sylabusy przedmiotów, jeśli przedmioty przez niego deklarowane są spoza politechniki warszawskiej, to niezbędne jest załączenie dodatkowo efektów kształcenia. Wniosek rozpatrzony jest przez Prodziekana ds. Studiów.";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/transfer.jpg' data-lightbox='example1'><img src='diagramy/transfer.jpg'/></a>";
    document.getElementById("proces").innerHTML +="<br><br><b>Złożenie podania o uznanie oceny:</b><br>Student przedstawia kartę przedmiotu oraz sylabusa Kierownikowi Przedmiotu. Kierownik może prośbę odrzucić, zwolnić studenta z zaliczania przedmiotu, bądź zwolnić z części materiału egzaminacyjnego";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/uznanie.png' data-lightbox='example1'><img src='diagramy/uznanie.png'/></a>";
    document.getElementById("proces").innerHTML +="<br><br> <b>Uwaga:</b><br>Jeśli przedmiot przepisywany jest sprzed kilku lat, wniosek może zostać odrzucony."
    
}

function umorzenie(){
    document.getElementById("proces").innerHTML = "<b>Złożenie podania o umorzenie za powtarzane zajęcia:</b><br>W momencie naliczenia opłat studentowi za niezdane przedmioty (zazwyczaj 3 tydzień studiów), może złożyć on podanie XYZ o umorzenie częściowe umorzenie płatność bądź rozłożenie płatności na raty. W uzasadnieniu w pierwszej kolejności student musi przedstawić powód niezaliczenia przedmiotów (przedmiot szczególnie trudny, wydarzenie losowe, sytuacja rodzinna, choroba itp.). Dopuszczalne jest wyjaśnienie dlaczego student ma problem z zapłatą. W momencie trudnej sytuacji materialnej niezbędne jest załączenie zaświadczenia o pobieraniu stypendium socjalnego (możliwe do uzyskania w Dziekanacie ds. Socjalnych) lub innych dokumentów świadczących o tymczasowym problemie. Podania bez uzasadnienia nie są rozpatrywane. Podanie składane jest w Dziekanacie ds. Socjalnych, następnie rozpatrzone przez Dziekana ds. Studentów. Student może odwołać się od decyzji Dziekana składając odwołanie od podania - dokument XYZ. Załączona zostanie instrukcja wypełniania podania.          <br>";
    document.getElementById("proces").innerHTML +="<br><b>Uwaga:</b><br>          Dotyczy tylko studentów o obywatelstwie polskim na studiach stacjonarnych. Opłata za konsultację pracy dyplomowej nie zostanie umorzona zgodnie z rozporządzeniem Rektora.";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/umorzenie.png' data-lightbox='example1'><img src='diagramy/umorzenie.png'/></a>";
}
function zajecia(){
    document.getElementById("proces").innerHTML = "<b>Zapis na zajęcia:</b><br>     <b>a)</b> Student pierwszego semestru nie musi podejmować żadnych działań - Dziekanat wykonuje wszystkie czynności <br>      <b>b)</b> Student wyższych semestrów musi zapisać się na Przedmiot i na Termin Zajęć. Rejestracja odbywa się dwuetapowo:<br><br><b>Etap I</b> - złożenie deklaracji przedmiotów, które Student chce studiować w danym semestrze w systemie ISOD. Po pozytywnym rozpatrzeniu deklaracji Student zostaje zapisany na Przedmiot i widzi przy deklarowanym Przedmiocie w deklaracji adnotację Zapisano. <br><br>"
    document.getElementById("proces").innerHTML +="<b>Uwaga:</b><br>Może się zdarzyć, że nie zostaniesz zapisany na Przedmiot - przyczyną może być na przykład brak miejsc (przedmioty obieralne mają zazwyczaj limit uczestników).<br><br>  ";
    document.getElementById("proces").innerHTML +="<b>Etap II</b> polega na zapisaniu się na Termin Zajęć. Jeśli Przedmiot jest w toku studiów Studenta i deklaracja została złożona w terminie, to zapis na Termin Zajęć odbędzie się automatyczni. Student zostaje zapisany na Termin zajęć wynikający z Jego przynależności do grupy dziekańskiej i planu zajęć.<br>       Jeśli została złożona korekta deklaracji lub przedmiot realizowany jest awansem, powtarzany, przedmiot jest spoza toku studiów Studenta, lub Student chce zapisać się na inny Termin Zajęć, to musi sam zapisać się na Termin zajęć. Dopiero w momencie gdy Prowadzący zgodzi się na udział Studenta w zajęciach i zaakceptuje go w systemie ISOD, Student ma prawo do udziału w takich Zajęciach i przystępowania do zaliczeń lub egzaminów z tego Przedmiotu.<br>        Decyzja Prowadzącego jest zazwyczaj uzależniona od liczby wolnych miejsc lub od ciągłości merytorycznej (może się zdarzyć, że przedmiot wymaga wiedzy z innego przedmiotu,, którego Student jeszcze nie miał) - Prowadzący każdą taką sytuację rozważa indywidualnie."
    document.getElementById("proces").innerHTML +="<br><br><b> Uwaga:</b><br>Jeśli Student nie uzyska zgody Prowadzącego na udział w Zajęciach, to musisz koniecznie i niezwłocznie złożyć korektę deklaracji, w której wykreśli przedmiot, na którego zajęcia się nie dostał.";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/Untitled.png' data-lightbox='example1'><img src='diagramy/Zapis%20na%20zaj%C4%99cia.png'/></a>";
}
function wznowienie(){
    document.getElementById("proces").innerHTML = "<b>Złożenie podania o wznowienie studiów:</b><br>Student, który przerwał studia może ubiegać się o ponowne zapisanie na uczelnię i kontynuowanie studiów w ramach tzw. Wznowienia na Studia. Po spełnieniu warunków określonych przez Dziekana Student może otrzymać rejestrację na kolejny semestr wynikający z jego dotychczasowego studiowania. Student następnie musi zdać egzamin wznawiający, zazwyczaj w okolicach sesji egzaminacyjnej. Oprócz egzaminu wznawiającego Dziekan może wyznaczyć dodatkowe przedmioty, które Student będzie musiał uzupełnić zanim otrzyma rejestrację na studia oraz przedmioty, które będzie musiał zaliczyć już po przywróceniu w prawach studenta.<br> Podanie o wznowienie na studia składamy na druku PD_156 dostępnym na stronie <a href='https://isod.ee.pw.edu.pl/isod-portal/dokumenty' target='_blank'>isod.ee.pw.edu.pl/isod-portal/dokumenty</a>. Podanie należy złożyć przed rozpoczęciem semestru zgodnie z terminarzem podanym w Kalendarzu Dziekanatu. "
    document.getElementById("proces").innerHTML +=" <br><br><b>Uwaga:</b><br>          Jeśli od chwili przerwania studiów minęło wiele lat (zazwyczaj wiele - to 3-4  lata), studia zostały przerwane w początkowym okresie studiów (np. po drugim semestrze) lub Student ma  duże zaległości w studiowaniu, to zazwyczaj nie otrzyma on zgody na wznowienie studiów. <br>Więcej informacji dotyczących wznawiania studiów dostępne jest w dokumencie PD_300 rozdział 10: <a href='https://isod.ee.pw.edu.pl/isod-portal/dokumenty' target='_blank'>isod.ee.pw.edu.pl/isod-portal/dokumenty</a>";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/wznowienie_studiow.png' data-lightbox='example1'><img src='diagramy/wznowienie_studiow.png'/></a>";
}
function przeniesienie(){
     document.getElementById("proces").innerHTML = "<b>Złożenie podania o przeniesienie na inny wydział/kierunek:</b><br>   Warunkiem zmiany kierunku studiów jest zaliczenie pierwszego roku studiów - jest to warunek konieczny. <br> Student chcący zmienić kierunek <u>w ramach wydziału</u> powinien złożyć podanie o przeniesienie na druku PD_157 dostępny na stronie <a href='https://isod.ee.pw.edu.pl/isod-portal/dokumenty' target='_blank'>isod.ee.pw.edu.pl/isod-portal/dokumenty</a> do Dziekana ds. Studentów. <br>W przypadku <u>zmiany wydziału</u>, Student powinien dołączyć do podania zaświadczenie o ukończeniu pierwszego roku studiów oraz wykaz zaliczonych przedmiotów wraz z ich sylabusami. Zaliczenie pierwszego roku nie jest równoważne z rejestracją na kolejny rok. Student musi wypełnić wszystkie wymogi określone dla pierwszego roku, a więc uzyskać wymaganą liczbę punktów ECTS i zaliczyć wszystkie przedmioty i bloki obowiązujące na pierwszym roku. Podanie o przeniesienie należy złożyć przed rozpoczęciem semestru zgodnie z terminarzem podanym w Kalendarzu Dziekanatu.";
    document.getElementById("proces").innerHTML +=" <br><br><b>Uwaga:</b><br>          Informacje o zaliczonych przedmiotach i ich programie posłużą do ustalenia przez Dziekana tzw. różnic programowych. Dziekan może wyznaczyć Studentowi dodatkowe przedmioty, które będzie musiał uzupełnić w toku swoich studiów. Student może mieć maksymalnie do nadrobienia przedmioty za 30 ECTS.";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/Przeniesienie.png' data-lightbox='example1'><img src='diagramy/Przeniesienie.png'/></a>";
}
function dyplom(){
    document.getElementById("proces").innerHTML = "<b>Proces dyplomowania:</b><br>Student rozpoczyna proces dyplomowania wyborem promotora, tematu oraz zakresu pracy. Gdy temat i zakres zostanie zaakceptowany przez Promotora, dane dotyczące prac wpisywane są w system ISOD. Następnie Promotor wydaje wraz ze Studentem dokument wydania tematu pracy PD_105 Kierownikowi zakładu (dokument dostępny na stronie <a href='https://isod.ee.pw.edu.pl/isod-portal/dokumenty' target='_blank'>isod.ee.pw.edu.pl/isod-portal/dokumenty</a>). <br>       Jeśli temat zostanie przyjęty przez Kierownika, Student może rozpocząć przygotowywanie pracy pod okien Promotora. W momencie gdy Promotor, nie ma już więcej uwag, praca zostaje przez niego przyjęta. Student prace drukuje i składa w zakładzie, w którym będzie się bronił, razem z wypaloną płytą CD z pracą (opisaną imieniem, nazwiskiem, numerem indeksu i tematem).<br>W systemie ISOD wprowadzana jest informacja o złożeniu pracy. Promotor zamieszcza na platformie również opinie dotyczącą pracy i ocenę. Kierownik Zakładu wyznacza termin obrony, skład komisji oraz recenzenta. Student jest zobowiązany do 7 dni przed obroną złożyć w dziekanacie niezbędne dokumenty opisane w dokumencie PD_104 dostępnym na stronie <a href='https://isod.ee.pw.edu.pl/isod-portal/dokumenty' target='_blank'>isod.ee.pw.edu.pl/isod-portal/dokumenty</a>. <br>         Następnie Student zamieszcza w systemie ISOD wersję elektroniczną pracy. Wydawana jest decyzja o dopuszczeniu do obrony, Recenzent zamieszcza w ISOD recenzję pracy i Student podchodzi do obrony pracy dyplomowej.";
    document.getElementById("proces").innerHTML +=" <br><br><b>Uwaga:</b><br>Niezbędne do złożenia dokumenty mogą różnić się w zależności od Zakładu."
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/dyplomowanie.jpg' data-lightbox='example1'><img src='diagramy/dyplomowanie.jpg'/></a>";
}
function dyplomPrzedluzenie(){
    document.getElementById("proces").innerHTML = "<b>Przedłużenie pracy dyplomowej:</b><br>Termin złożenia pracy dyplomowej na studiach II stopnia podany jest w Regulaminie Studiów i jest to 1 marca lub 15 września. <br><b>(§ 20. ust. 9) </b><br>Natomiast termin złożenia pracy na studiach I stopnia jest „ruchomy” i określany co roku przez Rektora w Kalendarzu Roku Akademickiego.<br><br>W przypadku jeśli Student nie zdąży złożyć pracy dyplomowej w obowiązującym terminie, może złożyć podanie o przedłużenie złożenia pracy dyplomowej na druku PD_111 dostępnym na stronie <a href='https://isod.ee.pw.edu.pl/isod-portal/dokumenty' target='_blank'>isod.ee.pw.edu.pl/isod-portal/dokumenty</a>. Należy  pamiętać, że warunkiem pozytywnego rozpatrzenia podania jest wpisanie przez Promotora do systemu ISOD tematu pracy oraz (AND) jego zaakceptowanie przez Kierownika Zakładu dyplomującego. Należy więc sprawdzić przed złożeniem podania, czy zapisy w ISOD są poprawne.<br><br>         W przypadku nie złożenia pracy i nie wystąpienia z podaniem o przedłużenie złożenia pracy, Student zostanie skreślony ze studiów nawet jeśli będzie miał zaliczone wszystkie przedmioty. W takim wypadku traci prawa studenta i może przystąpić do obrony ubiegając się o wznowienie na obronę pracy dyplomowej.<br><br>            W decyzji o przedłużeniu złożenia pracy dyplomowej podany jest termin obowiązywania tej decyzji. Do tego terminu praca musi być przyjęta przez promotora, a fakt ten odnotowany w systemie ISOD. Jeśli Student nie dotrzyma przedłużonego terminu zostanie deﬁnitywnie skreślony z listy studentów.<br><br>"
    document.getElementById("proces").innerHTML +="<b>Uwaga:</b><br>     Termin złożenia pracy to dzień, w którym Promotor odnotowuje w systemie przyjęcie pracy. NIE jest to termin obrony. Od dnia przyjęcia pracy do dnia obrony może upłynąć sporo czasu. Zazwyczaj jest to kilkanaście dni.";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/Przedluzenie_pracy.png' data-lightbox='example1'><img src='diagramy/Przedluzenie_pracy.png'/></a>";
}
function deklaracja(){
    document.getElementById("proces").innerHTML = "<b>Złożenie deklaracji na semestr akademicki:</b><br>W pierwszej kolejności, student w systemie ISOD składa deklarację wstępną ok. 2 miesiące przed rozpoczęciem semestru. Ma ona na celu zweryfikowanie zainteresowania w przedmiotach obieralnych. Deklaracja przyjmowana jest przez pracownika dziekanatu i student otrzymuje maila z potwierdzeniem przyjęcia deklaracji.<br>Tuż przed rozpoczęciem semestru, student składa deklarację. Analogicznie deklaracja przyjmowana jest przez pracownika dziekanatu i informację o jej przyjęciu student otrzymuje na maila.Student zostaje automatycznie zapisany na zajęcia zgodnie ze swoją deklaracją oraz grupą dziekańską. <br>Student ma prawo do złożenia w systemie ISOD korekty deklaracji w czasie trwania 1 tygodnia zajęć. Tak jak wcześniej, korekta przyjmowana jest przez pracownika dziekanatu, a student otrzymuje informację na maila."
    document.getElementById("proces").innerHTML +=" <br><br> <b>Uwaga:</b><br>          Student, który składa korektę deklaracji w czasie trwania 1 tygodnia zajęć, zmuszony jest do samodzielnego <b>Zapisu na zajęcia</b>.<br>Student, może wprowadzić korekty w deklaracji, również w czasie trwania 2 tygodnia zajęć, jednak wtedy podanie korekta musi być zatwierdzona przez Prodziekana ds. Studiów. Prodziekan może korektę przyjąć lub odrzucić. Analogicznie student musi sam zapisać się na zajęcia.";
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/Deklaracje.jpg' data-lightbox='example1'><img src='diagramy/Deklaracje.jpg'/></a>";
}
function specjalnosc(){
    document.getElementById("proces").innerHTML = "<b>Wybór specjalności:</b><br>Student składa preferencje dotyczące specjalności/specjalizacji w systemie ISOD. Następnie system automatycznie przypisuje studenta na specjalność/specjalizację zgodnie z uzyskaną średnią za postępy w nauce. <br> W przypadku chęci zmiany specjalności/specjalizacji Student składa podanie do Kierownika Specjalności, na którą chce się przenieść. Zgoda Opiekuna Specjalności jest konieczna. Następnie Student składa podanie do Prodziekana ds. Studiów na druku ogólnym PD_150 dostępny na stronie <a href='https://isod.ee.pw.edu.pl/isod-portal/dokumenty' target='_blank'>isod.ee.pw.edu.pl/isod-portal/dokumenty</a>. Do podania należy dołączyć zgodę Opiekuna Specjalności. Prodziekan podejmuje ostateczną decyzję o przeniesieniu.";
    document.getElementById("proces").innerHTML +=" <br><br> <b>Uwaga:</b><br>      Zmiana specjalności/specjalizacji może się też wiązać z uzupełnieniem przedmiotów specjalności/specjalizacji.";   
    document.getElementById("proces").innerHTML +="<br><br>"   +"<a href='diagramy/specjalnosc.png' data-lightbox='example1'><img src='diagramy/specjalnosc.png'/></a>";
}